spring:
  application:
    name: legou-eureka-cluster
---
spring:
  profiles: discovery1
server:
  port: 8081
eureka:
  instance:
    hostname: 10.58.93.148:8081
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8083/eureka/,http://127.0.0.1:8082/eureka/
---
spring:
  profiles: discovery2
server:
  port: 8082
eureka:
  instance:
    hostname: 10.58.93.148:8082
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8081/eureka/,http://127.0.0.1:8083/eureka/
---
spring:
  profiles: discovery3
server:
  port: 8083
eureka:
  instance:
    hostname: 10.58.93.148:8083
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8082/eureka/,http://127.0.0.1:8081/eureka/
