spring:
  application:
    name: zipkin-server
  sleuth:
    enabled: false
  cloud:
    bus:
      enabled: true
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers: 10.58.93.148:9092
          zk-nodes: 10.58.93.148:2181
server:
  port: 9888
