spring:
  application:
    name: zipkin-server
#  sleuth:
#    enabled: false
#  cloud:
##    bus:
##      enabled: true
#    stream:
#      default-binder: kafka
#      kafka:
#        binder:
#          brokers: 10.58.93.148:9092
#          zk-nodes: 10.58.93.148:2181
#        queue: zipkin
#
zipkin:
  collector:
    kafka:
      zookeeper: 10.58.93.148:2181
#zipkin:
#  collector:
#    rabbitmq:
#      addresses: 10.58.93.148:5672
#      queue: zipkin

server:
  port: ${SERVER_PORT:9888}
logging:
  level.org.springframework.cloud: DEBUG
