eureka:
  instance:
    prefer-ip-address: true
    ip-address: ${SERVER_IP:10.58.93.148}
  client:
    serviceUrl:
      defaultZone: http://10.58.93.148:8081/eureka/,http://10.58.93.148:8082/eureka/,http://10.58.93.148:8083/eureka/
server:
  port: ${SERVER_PORT:8761}
spring:
  application:
    name: legou-server
  sleuth:
    sampler:
      percentage: 1.0
#  zipkin:
#    base-url: http://10.58.93.148:9888
  cloud:
    bus:
      enabled: true
    config:
      label: master
      discovery:
        enabled: true
        service-id: config-server
      profile: dev
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers: 10.58.93.148:9092
          zk-nodes: 10.58.93.148:2181
#  rabbitmq:
#    host: 10.58.93.148
#    port: 5672
#  kafka:
#    bootstrap-servers: 10.58.93.148:9092
logging.level.org.springframework.cloud.sleuth: DEBUG
logging.level.org.springframework.web.servlet.DispatcherServlet: DEBUG