eureka:
  client:
    serviceUrl:
      defaultZone: http://10.58.93.148:8081/eureka/,http://10.58.93.148:8082/eureka/,http://10.58.93.148:8083/eureka/
server:
  port: 8869
spring:
  application:
    name: legou-zuul
zuul:
  filter:
    root: “/work/zuul/filter/groovy”
    refreshInterval: 5
  routes:
    legou-server:
      path: /api-a/**
      serviceId: legou-server
    legou-api: /api-b/**
    legou-server1:
      path: /api-c/**
      serviceId: legou-server